image: node:latest
staging:
 type: deploy
#  stage: build
 image: ruby:latest
 script:
   - apt-get update -qy
   - apt-get install -y ruby-dev
   - gem install dpl
   - dpl --provider=heroku --app=lupa-web-v1 --api-key=$HEROKU_API_KEY
 only:
   - developer